#!/usr/bin/env python3
"""
build_task.py — turn a DeFiHackLabs PoC + verified on-chain source into a
self-contained, offline-replayable evmpatch task directory.

A task directory has this layout (see tasks/ngp_2025_09 for a real one):

    tasks/<task_id>/
    ├── task.json                 # metadata + hash-locks + allow-list (this file writes it)
    ├── project/                  # the Foundry project the agent edits
    │   ├── foundry.toml          #   [rpc_endpoints] alias -> ${TASK_RPC_URL}
    │   ├── remappings.txt
    │   ├── src/                  #   PATCHABLE source (verified on-chain source)
    │   └── lib/forge-std
    ├── tests/                    # HARNESS — hash-locked, copied in read-only at reward
    │   ├── poc.t.sol             #   exploit oracle: PASS on vuln, must FAIL on a fix
    │   └── hidden/
    │       ├── regression.t.sol  #   hand-written functionality invariants
    │       └── invariants_auto.t.sol  # AUTO-GENERATED compile + selector invariants
    ├── state/                    # frozen chain state for no-network replay
    │   ├── rpc_log.json          #   record/replay proxy log (superset: poc + hidden)
    │   ├── anvil_state.json      #   anvil_dumpState (optional / best-effort)
    │   └── rpc_cache/            #   Foundry RPC cache (FOUNDRY_OFFLINE fallback)
    └── reference_patch.sol.diff  # known-good fix; CI self-test only, NEVER shown to agent

BUILD PHASE (network available) — high level:
  1. Assemble project/ from verified source (fetch_sources.py output) + libs.
  2. Write poc.t.sol from the DeFiHackLabs PoC, rewired to the state-replay model:
       vm.createSelectFork(TASK_FORK_URL, block); vm.etch(victim, getDeployedCode(patchable))
     and an *exploit oracle* assertion (attacker profit > threshold) that FAILS post-fix.
  3. auto-generate tests/hidden/invariants_auto.t.sol from the ORIGINAL contract's
     public/external selectors (signature invariance) + a compile check.
  4. Warm the frozen state: run `rpc_replay.py record <rpc> state/rpc_log.json` and
     execute the WHOLE suite (poc + hidden) once so every slot either test touches is
     captured. (anvil --load-state is also attempted but is unreliable across chains —
     the record/replay proxy is the primary mechanism; see tasks/BUILD_LOG.md.)
  5. Emit task.json: metadata, temporal-split label, SHA-256 hash-locks of every harness
     file, and the allow-list of patchable source globs.

This module is import-safe (pure helpers) and also runnable as a CLI for step 3 & 5 on an
already-assembled task dir:  `python -m evmpatch_env.build_task finalize tasks/ngp_2025_09`
"""
from __future__ import annotations

import hashlib
import json
import shutil
import re
import subprocess
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path

# --- temporal split (hard rule) -------------------------------------------------------
# Training: PoCs dated 2025-12 or earlier. Held-out TEST: 2026-03 .. 2026-08 (never train).
TRAIN_MAX = "2025-12"
TEST_RANGE = ("2026-03", "2026-08")


def split_for_month(month: str) -> str:
    """month is 'YYYY-MM'. Returns 'train', 'test', or 'excluded'."""
    if month <= TRAIN_MAX:
        return "train"
    if TEST_RANGE[0] <= month <= TEST_RANGE[1]:
        return "test"
    # 2026-01/02 fall in neither bucket — quarantine rather than silently train on them.
    return "excluded"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def hash_lock_dir(root: Path, rel_globs: list[str]) -> dict[str, str]:
    """SHA-256 every file matched by rel_globs, keyed by path relative to root."""
    locks: dict[str, str] = {}
    for g in rel_globs:
        for p in sorted(root.glob(g)):
            if p.is_file():
                locks[str(p.relative_to(root))] = sha256_file(p)
    return locks


def contract_selectors(project_dir: Path, contract_ref: str) -> dict[str, str]:
    """methodIdentifiers of a contract via `forge inspect`. contract_ref e.g. 'Token.sol:Token'."""
    out = subprocess.run(
        ["forge", "inspect", contract_ref, "methodIdentifiers", "--json"],
        cwd=project_dir, capture_output=True, text=True,
    )
    if out.returncode != 0:
        raise RuntimeError(f"forge inspect failed: {out.stderr[-400:]}")
    return json.loads(out.stdout or "{}")


# --- auto-generated hidden invariant test ---------------------------------------------
AUTO_HEADER = """// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

// HARNESS FILE — hash-locked, read-only. *** AUTO-GENERATED by build_task.py — DO NOT EDIT ***
// Signature-invariance + compile invariants: a valid patch may change the *body* of the
// vulnerable contract but must not delete or re-type its public/external ABI, and the
// project must still compile (implicit: getDeployedCode below reverts if it does not).
// These PASS on both the vulnerable and a correctly-patched contract; a "delete the
// function" or "brick the contract" shortcut trips them and scores 0.
//
// The selector check reads the dispatch table itself rather than a proxy for it such as
// `VICTIM.code.length > 0` (true for any non-empty contract, so it would prove nothing).
// It walks the runtime bytecode as EVM code (skipping PUSH immediates so a selector cannot
// be forged by data that merely looks like an opcode) and records every PUSH4 immediate.
// Solidity emits the dispatch table as
// `PUSH4 <selector>; EQ; PUSH2 <dest>; JUMPI`, so a selector that is absent from that set
// is absent from the ABI. `test_selector_check_is_not_vacuous` asserts a selector that
// cannot be in the table is reported absent, so the check cannot silently degrade to
// always-true.
//
// A PUSH4 immediate is NECESSARY but not SUFFICIENT (it could be dead data, and a proxy or
// catch-all fallback could dispatch selectors that are not in the table at all). So there is
// a SECOND, behavioural check: `test_abi_selectors_dispatch` actually CALLS every required
// function with well-formed zero-valued calldata and asserts the contract does not answer
// with the "no such function" signature (failure + empty returndata, i.e. the dispatcher's
// `revert(0,0)`). `test_unknown_selector_is_rejected` is its control: an impossible selector
// MUST produce that signature, which is what makes the behavioural check meaningful. The
// grade records both checks separately (RewardResult.abi_invariants).
//
// The bytecode half is deliberately CONSERVATIVE in the accept direction: PUSH1..PUSH4 are
// all indexed because solc strips leading zero bytes from push constants, so a small
// constant can coincide with a selector that has leading zero bytes. That can only produce
// a false "present", never a false "absent" -- and the behavioural half is what closes that
// gap, since a selector that is merely present as data will not dispatch.
"""


def _top_level_arg_count(sig: str) -> int:
    """Number of top-level ABI parameters in a signature like `f(uint256,(a,b)[],bool)`."""
    inner = sig[sig.index("(") + 1: sig.rindex(")")]
    if not inner.strip():
        return 0
    depth, n = 0, 1
    for ch in inner:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "," and depth == 0:
            n += 1
    return n


def render_auto_invariants(victim_addr: str, selectors: dict, block: int,
                           artifact_ref: str = "Token.sol:Token") -> str:
    checks, dispatch, calibrate = [], [], []
    for sig, sel in sorted(selectors.items(), key=lambda kv: kv[1]):
        n = _top_level_arg_count(sig)
        checks.append(f'        _assertHasSelector(hex"{sel}", "{sig}");')
        dispatch.append(f'        _assertSelectorDispatches(hex"{sel}", {n}, "{sig}");')
        calibrate.append(f'        _note(hex"{sel}", {n});')
    checks_block = "\n".join(checks)
    dispatch_block = "\n".join(dispatch)
    calibrate_block = "\n".join(calibrate)
    return f"""{AUTO_HEADER}
import "forge-std/Test.sol";

contract AutoInvariants is Test {{
    address constant VICTIM = {victim_addr};
    uint256 constant FORK_BLOCK = {block};

    // every PUSH1..PUSH4 immediate found in the victim's runtime bytecode
    mapping(bytes4 => bool) internal push4;
    uint256 internal push4Count;
    // which selectors the ORIGINAL deployed contract answers under a zero-argument probe
    mapping(bytes4 => bool) internal originalDispatches;
    uint256 internal calibratedCount;
    uint256 internal excludedCount;

    function setUp() public {{
        string memory url = vm.envOr("TASK_FORK_URL", string("bsc"));
        try vm.createSelectFork(url, FORK_BLOCK) {{ }} catch {{ vm.createSelectFork(url); }}

        // CALIBRATE FIRST, against the contract that is actually deployed on the fork.
        // The dispatch probe's "no such function" signature (call fails, no returndata) is
        // also what a function produces when it reverts with no reason -- e.g. a call into
        // a zero address argument. Recording which selectors the ORIGINAL contract answers
        // turns the check into the property we actually want: every selector the deployed
        // contract dispatches must still be dispatched after the patch. Selectors the
        // original itself cannot answer under a zero-argument probe are excluded and
        // counted, so the exclusion is visible rather than silent.
        _calibrate();

        // getDeployedCode compiles the patchable source; if the patch breaks compilation
        // this reverts and every invariant below fails -> reward 0 (compile gate).
        vm.etch(VICTIM, vm.getDeployedCode("{artifact_ref}"));
        _indexPush4(VICTIM.code);
    }}

    /// @dev Linear EVM code walk. The immediate of every PUSHn is skipped rather than
    ///      rescanned, so a selector-shaped run of bytes inside (say) a PUSH32 constant is
    ///      NOT counted. PUSH1..PUSH4 are all indexed, not just PUSH4: solc strips leading
    ///      zero bytes from push constants, so a selector like balanceOf(address,uint256)
    ///      = 0x00fdd58e is emitted as `PUSH3 0xfdd58e`. Zero is never indexed (it is not a
    ///      real selector and PUSH1 0x00 is everywhere).
    function _indexPush4(bytes memory code) internal {{
        uint256 i = 0;
        uint256 n = code.length;
        while (i < n) {{
            uint8 op = uint8(code[i]);
            if (op >= 0x60 && op <= 0x63) {{            // PUSH1..PUSH4
                uint256 width = uint256(op) - 0x5f;
                if (i + width < n) {{
                    uint32 v = 0;
                    for (uint256 k = 1; k <= width; k++) {{
                        v = (v << 8) | uint32(uint8(code[i + k]));
                    }}
                    if (v != 0) {{
                        bytes4 sel = bytes4(v);
                        if (!push4[sel]) {{ push4[sel] = true; push4Count++; }}
                    }}
                }}
            }}
            if (op >= 0x60 && op <= 0x7f) {{     // PUSH1..PUSH32: skip the immediate
                i += 1 + (uint256(op) - 0x5f);
            }} else {{
                i += 1;
            }}
        }}
    }}

    function _assertHasSelector(bytes4 sel, string memory sig) internal view {{
        assertTrue(push4[sel],
            string.concat("ABI broken: selector absent from runtime bytecode: ", sig));
    }}

    function test_abi_selectors_preserved() public view {{
{checks_block}
    }}

    // ---------------------------------------------------------------- behavioural check
    // A PUSH4 immediate proves the bytes are there; it does not prove the contract answers
    // the call. Probe every required function with well-formed, zero-valued calldata (one
    // 32-byte word per top-level parameter, which decodes to zeros for value types and to
    // empty for dynamic ones) and reject the dispatcher's "no such function" signature.

    /// @dev The "no such function" answer of a Solidity dispatcher is `revert(0, 0)`: the
    ///      call FAILS and returns NO data. Anything else -- success, a require string, a
    ///      custom error -- means the function exists and ran.
    function _probe(bytes4 sel, uint256 nargs) internal returns (bool ok, uint256 retlen) {{
        bytes memory data = abi.encodePacked(sel, new bytes(32 * nargs));
        bytes memory ret;
        (ok, ret) = VICTIM.call{{gas: 3000000}}(data);
        retlen = ret.length;
    }}

    function _dispatches(bytes4 sel, uint256 nargs) internal returns (bool) {{
        (bool ok, uint256 retlen) = _probe(sel, nargs);
        return ok || retlen > 0;   // anything but the dispatcher's bare revert(0, 0)
    }}

    function _calibrate() internal {{
{calibrate_block}
    }}

    function _note(bytes4 sel, uint256 nargs) internal {{
        if (_dispatches(sel, nargs)) {{
            originalDispatches[sel] = true;
            calibratedCount++;
        }} else {{
            excludedCount++;
        }}
    }}

    function _assertSelectorDispatches(bytes4 sel, uint256 nargs, string memory sig) internal {{
        if (!originalDispatches[sel]) {{
            return;   // the deployed contract could not answer this probe either
        }}
        assertTrue(_dispatches(sel, nargs),
            string.concat("ABI broken: contract does not dispatch ", sig));
    }}

    /// Control for the probe above. An impossible selector MUST get the "no such function"
    /// answer; if it does not, the contract has a catch-all fallback and dispatch probing
    /// proves nothing, so the whole behavioural check is void and must fail loudly.
    function test_unknown_selector_is_rejected() public {{
        (bool ok, uint256 retlen) = _probe(bytes4(hex"deadf00d"), 0);
        assertFalse(ok, "impossible selector accepted: catch-all fallback, dispatch probe meaningless");
        assertEq(retlen, 0, "impossible selector returned data: dispatch probe meaningless");
    }}

    function test_abi_selectors_dispatch() public {{
        assertGt(calibratedCount, 0,
            "calibration answered nothing: the behavioural ABI check has no baseline");
{dispatch_block}
    }}

    /// The selector check must be able to say NO. A selector that no compiler would emit
    /// into this dispatch table must be reported absent; if this fails, the check above
    /// has degenerated into a tautology and every ABI result from it is worthless.
    function test_selector_check_is_not_vacuous() public view {{
        assertGt(push4Count, 0, "no PUSH4 immediates indexed: the code walk is broken");
        assertFalse(push4[bytes4(hex"deadf00d")], "vacuous selector check: bogus selector reported present");
        assertFalse(push4[bytes4(hex"00000000")], "vacuous selector check: zero selector reported present");
    }}

    function test_contract_has_code() public view {{
        assertGt(VICTIM.code.length, 0, "patched contract has no deployed code");
    }}
}}
"""



# --- project scaffolding --------------------------------------------------------------
DEFAULT_REMAPPINGS = "forge-std/=lib/forge-std/src/\n"


def foundry_toml(solc: str | None = None, optimizer: bool = True, runs: int = 200,
                 evm_version: str = "shanghai", rpc_alias: str = "chain") -> str:
    """The project's foundry.toml. Pin the compiler to the settings the contract was
    VERIFIED with wherever possible: the grader etches code compiled from this project
    onto the live forked address, so a different compiler is a different contract.
    Leave `solc` unset only when the project mixes major Solidity versions (an old victim
    contract plus modern forge-std), where Foundry must pick per file."""
    pin = f"solc = '{solc}'\n" if solc else ""
    return (
        "[profile.default]\n"
        "src = 'src'\ntest = 'test'\nout = 'out'\nlibs = ['lib']\n"
        f"{pin}"
        f"evm_version = '{evm_version}'\n"
        f"optimizer = {str(optimizer).lower()}\n"
        f"optimizer_runs = {runs}\n"
        'fs_permissions = [{ access = "read", path = "./" }]\n'
        "\n[rpc_endpoints]\n"
        f'{rpc_alias} = "${{TASK_RPC_URL}}"\n'
    )


def scaffold_project(task_dir: Path, src_files: dict, toml: str,
                     forge_std_from: Path, remappings: str = DEFAULT_REMAPPINGS) -> Path:
    """Create tasks/<id>/{project,tests/hidden,state} and drop the patchable source in.

    src_files maps a project-relative path ("src/contracts/Token.sol") to file content.
    forge_std_from points at an existing `lib/forge-std` to copy, so a task directory is
    self-contained and does not need `forge install` (and therefore no network) to build.
    """
    task_dir = Path(task_dir)
    project = task_dir / "project"
    for d in (project / "src" / "contracts", project / "lib",
              task_dir / "tests" / "hidden", task_dir / "state"):
        d.mkdir(parents=True, exist_ok=True)
    (project / "foundry.toml").write_text(toml)
    (project / "remappings.txt").write_text(remappings)
    dst = project / "lib" / "forge-std"
    if not dst.exists():
        shutil.copytree(forge_std_from, dst)
    for rel, content in src_files.items():
        f = project / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(content)
    return task_dir


# --- expected-test manifest -----------------------------------------------------------
# The scorer refuses to award `solved` unless the set of test ids that actually executed
# is EXACTLY the set this file declares. Without it, "some tests passed and none failed"
# was enough — which a partial suite, an unrelated test, or a crashed runner all satisfy.
MANIFEST_ID_FORMAT = "<test file path>:<contract>:<function signature>"


def list_executed_test_ids(workdir: Path, match_path: str, fork_url: str) -> list[str]:
    """Fully qualified ids of the tests forge actually ran for `match_path`.

    Derived from a real `forge test --json` report rather than from `--list`, because the
    report is what the grader compares against and only the report carries the exact
    `fn(argtypes)` spelling that fuzz/parameterised tests produce.
    """
    import os
    env = dict(os.environ)
    env.update({"TASK_FORK_URL": fork_url, "FOUNDRY_OFFLINE": "true",
                "FOUNDRY_NO_STORAGE_CACHING": "true", "NO_COLOR": "1"})
    out = subprocess.run(["forge", "test", "--match-path", match_path, "--json"],
                         cwd=workdir, capture_output=True, text=True, env=env)
    try:
        blob = json.loads(out.stdout.strip())
    except Exception as exc:
        raise RuntimeError(f"forge --json report unparseable for {match_path}: {exc}\n"
                           f"{out.stdout[-800:]}\n{out.stderr[-400:]}")
    ids = []
    for suite, sdata in blob.items():
        for fn, tdata in (sdata.get("test_results") or {}).items():
            if fn.startswith("setUp("):
                raise RuntimeError(f"{suite} setUp() failed while building the manifest: "
                                   f"{tdata.get('reason')}")
            ids.append(f"{suite}:{fn}")
    return sorted(ids)


def build_manifest_offline(task_dir: Path, exploit_oracle_fn: str = "testExploit()",
                           accepted_block_kinds: list[str] | None = None,
                           patch_rel: str = "src/contracts/Token.sol") -> dict:
    """Derive tests/manifest.json by running the WHOLE suite against the task's own frozen
    state (offline, via the fail-closed replay proxy) and reading forge's --json report.

    Deriving it from a real run rather than from a static list means the manifest can only
    ever name tests that actually execute under the exact conditions the grader uses.
    """
    import shutil as _shutil
    import tempfile as _tempfile
    import uuid as _uuid
    from . import sandbox

    task_dir = Path(task_dir)
    root = Path(_tempfile.gettempdir()) / f"evmpatch_manifest_{_uuid.uuid4().hex}"
    root.mkdir(parents=True, exist_ok=True)
    work = root / "work"
    port_file, miss_file = root / "proxy.port", root / "rpc_misses.json"
    proxy = subprocess.Popen(
        [sys.executable, str(sandbox.RPC_REPLAY), "replay",
         str(task_dir / "state" / "rpc_log.json"), "0",
         "--port-file", str(port_file), "--miss-file", str(miss_file)],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    try:
        bound = sandbox._await_proxy(proxy, port_file, deadline_s=20.0)
        if bound is None:
            raise RuntimeError("replay proxy did not bind while building the manifest")
        sandbox.assemble_workdir(task_dir, None, work)
        url = f"http://127.0.0.1:{bound}"
        poc_ids = list_executed_test_ids(work, "test/poc.t.sol", url)
        hidden_ids = list_executed_test_ids(work, "test/hidden/*", url)
        observed = observed_block_reason(task_dir, url, work, exploit_oracle_fn, patch_rel)
    finally:
        proxy.terminate()
        try:
            proxy.wait(timeout=5)
        except Exception:
            proxy.kill()
        _shutil.rmtree(root, ignore_errors=True)

    oracle = [i for i in poc_ids if i.endswith(":" + exploit_oracle_fn)]
    if len(oracle) != 1:
        raise RuntimeError(f"expected exactly one {exploit_oracle_fn} among {poc_ids}")
    reasons = ["*assertion failed*", "*exploit did not yield profit*"]
    if observed and observed not in reasons:
        reasons.append(observed)
    print(f"[build_task] recognised 'exploit blocked' reasons: {reasons}")
    return write_manifest(task_dir, poc_ids, hidden_ids, oracle[0], accepted_block_kinds,
                          recognised_block_reasons=reasons)


def apply_unified_diff(original: str, diff_text: str) -> str:
    """Apply a single-file unified diff. Deliberately tiny and dependency-free (CI does not
    need GNU patch); every context and removal line is verified before anything is written."""
    lines = original.splitlines(keepends=True)
    diff_lines = diff_text.splitlines(keepends=True)
    offsets, pos = [], 0
    for ln in diff_lines:
        offsets.append(pos)
        pos += len(ln)
    starts = [(m.start(), m) for m in
              re.finditer(r"^@@ -(\d+)(?:,\d+)? \+\d+(?:,\d+)? @@.*$", diff_text, re.M)]
    if not starts:
        raise ValueError("no hunks in diff")
    out, src = [], 0
    for idx, (offset, m) in enumerate(starts):
        first = int(m.group(1)) - 1
        body_start = offsets.index(offset) + 1
        body_end = offsets.index(starts[idx + 1][0]) if idx + 1 < len(starts) else len(diff_lines)
        out.extend(lines[src:first])
        src = first
        for raw in diff_lines[body_start:body_end]:
            if raw.startswith("\\"):                     # "\ No newline at end of file"
                continue
            tag, text = raw[:1], raw[1:]
            if tag == " ":
                if lines[src] != text:
                    raise ValueError(f"diff context mismatch at line {src + 1}")
                out.append(lines[src]); src += 1
            elif tag == "-":
                if lines[src] != text:
                    raise ValueError(f"diff removal mismatch at line {src + 1}")
                src += 1
            elif tag == "+":
                out.append(text)
            else:
                raise ValueError(f"unexpected diff line: {raw!r}")
    out.extend(lines[src:])
    return "".join(out)


def observed_block_reason(task_dir: Path, fork_url: str, work: Path, oracle_fn: str,
                          patch_rel: str) -> str | None:
    """Run the PoC against the REFERENCE patch and report why the exploit oracle failed.

    That reason string is what the task then declares as a recognised "exploit blocked"
    signal. Anything else the grader sees later is `unrecognised_failure` -> inconclusive,
    so a PoC that starts failing for a NEW reason gets a human, not a reward.
    """
    diff_path = task_dir / "reference_patch.sol.diff"
    if not diff_path.exists():
        return None
    target = work / patch_rel
    original = target.read_text()
    try:
        target.write_text(apply_unified_diff(original, diff_path.read_text()))
        from . import sandbox
        run, _ = sandbox._run_forge(work, "test/poc.t.sol", fork_url, 600)
        hit = [t for t in run.tests.values() if t.name == oracle_fn]
        if len(hit) == 1 and hit[0].status == "Failure":
            return hit[0].reason
        return None
    finally:
        target.write_text(original)


def write_manifest(task_dir: Path, poc_ids: list[str], hidden_ids: list[str],
                   exploit_oracle: str,
                   accepted_block_kinds: list[str] | None = None,
                   recognised_block_reasons: list[str] | None = None) -> dict:
    """Emit tests/manifest.json — the expected-test contract for one task."""
    if exploit_oracle not in poc_ids:
        raise ValueError(f"exploit oracle {exploit_oracle!r} not among the PoC tests {poc_ids}")
    manifest = {
        "version": 1,
        "id_format": MANIFEST_ID_FORMAT,
        "poc": {
            "exploit_oracle": exploit_oracle,
            "tests": sorted(poc_ids),
            "count": len(poc_ids),
            # A failing oracle only counts as "exploit blocked" when it failed in the test
            # BODY. "assertion" = the profit assertion tripped; "revert" = the exploit path
            # itself reverted (e.g. the flash loan can no longer be repaid). Infrastructure
            # failures are never accepted; tighten to ["assertion"] for a task whose PoC
            # should always reach its assertion.
            "accepted_block_kinds": accepted_block_kinds or ["assertion", "revert"],
            # fnmatch patterns. A failing oracle whose reason matches NONE of these is
            # `unrecognised_failure` -> inconclusive, never a reward. The concrete revert
            # string is observed from a real run of reference_patch.sol.diff at build time.
            "recognised_block_reasons": recognised_block_reasons or ["*assertion failed*"],
        },
        "hidden": {"tests": sorted(hidden_ids), "count": len(hidden_ids)},
    }
    (task_dir / "tests" / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


# --- task.json ------------------------------------------------------------------------
@dataclass
class TaskMeta:
    task_id: str
    incident: str
    source: str                      # DeFiHackLabs relative path of the PoC
    chain: str
    chain_id: int
    fork_block: int
    rpc_alias: str
    date_month: str                  # YYYY-MM of the incident
    split: str                       # train | test | excluded
    vulnerability_class: str
    victim_address: str
    patchable_globs: list[str]       # allow-list: only these may change in the diff
    patch_contract_ref: str          # e.g. src/contracts/Token.sol:Token
    harness_files: list[str]         # relative paths that are hash-locked & read-only
    hash_locks: dict[str, str] = field(default_factory=dict)
    episode_budget: int = 30
    offline_mechanism: str = "rpc_replay_proxy"   # primary; anvil_load_state is fallback
    notes: str = ""


def write_task_json(task_dir: Path, meta: TaskMeta) -> None:
    (task_dir / "task.json").write_text(json.dumps(asdict(meta), indent=2) + "\n")


def finalize(task_dir: Path, meta_seed: dict) -> TaskMeta:
    """Generate auto-invariants + task.json for an already-assembled task dir.

    meta_seed provides the incident-specific fields; hashes + selectors are computed here.
    """
    task_dir = Path(task_dir)
    project = task_dir / "project"

    # 1) auto-generate the signature-invariance hidden test from ORIGINAL selectors
    # A task names its own patchable contract; the ngp defaults keep older seeds working.
    patch_ref = meta_seed.get("patch_contract_ref", "src/contracts/Token.sol:Token")
    patch_rel, contract_name = patch_ref.split(":")
    artifact_ref = f"{Path(patch_rel).name}:{contract_name}"
    selectors = contract_selectors(project, patch_ref)
    auto = render_auto_invariants(meta_seed["victim_address"], selectors,
                                  meta_seed["fork_block"], artifact_ref)
    (task_dir / "tests" / "hidden" / "invariants_auto.t.sol").write_text(auto)

    # 2) derive the expected-test manifest from a real offline run of the whole suite.
    #    Must come AFTER the auto-invariants are (re)written, or the manifest would omit
    #    them; must come BEFORE hash-locking, because the manifest is part of the harness.
    if not meta_seed.get("skip_manifest"):
        m = build_manifest_offline(task_dir,
                                   exploit_oracle_fn=meta_seed.get("exploit_oracle_fn",
                                                                   "testExploit()"),
                                   patch_rel=patch_rel)
        print(f"[build_task] manifest: {m['poc']['count']} poc + {m['hidden']['count']} hidden test ids")

    # 3) hash-lock the harness (poc + all hidden + foundry config + remappings)
    harness_globs = [
        "tests/poc.t.sol",
        "tests/hidden/*.sol",
        "tests/manifest.json",       # the expected-test contract is part of the harness
        "project/foundry.toml",
        "project/remappings.txt",
    ]
    locks = hash_lock_dir(task_dir, harness_globs)

    meta = TaskMeta(
        task_id=meta_seed["task_id"],
        incident=meta_seed["incident"],
        source=meta_seed["source"],
        chain=meta_seed["chain"],
        chain_id=meta_seed["chain_id"],
        fork_block=meta_seed["fork_block"],
        rpc_alias=meta_seed["rpc_alias"],
        date_month=meta_seed["date_month"],
        split=split_for_month(meta_seed["date_month"]),
        vulnerability_class=meta_seed["vulnerability_class"],
        victim_address=meta_seed["victim_address"],
        patchable_globs=meta_seed.get("patchable_globs", ["src/contracts/*.sol"]),
        patch_contract_ref=patch_ref,
        harness_files=sorted(locks.keys()),
        hash_locks=locks,
        episode_budget=meta_seed.get("episode_budget", 30),
        notes=meta_seed.get("notes", ""),
    )
    write_task_json(task_dir, meta)
    return meta


# NGP incident seed (BSC, 2025-09) — the prototyped task.
NGP_SEED = dict(
    task_id="ngp_2025_09",
    incident="NGP token price manipulation via sync() in _update()",
    source="src/test/2025-09/NGP_exp.sol",
    chain="bsc",
    chain_id=56,
    fork_block=61515894,
    rpc_alias="bsc",
    date_month="2025-09",
    vulnerability_class="amm-reserve-manipulation / mid-transfer-sync",
    victim_address="0xd2F26200cD524dB097Cf4ab7cC2E5C38aB6ae5c9",
    patchable_globs=["src/contracts/*.sol"],
    episode_budget=30,
    notes=(
        "Sell path drained treasury+reward from the pair then called pair.sync() inside the "
        "seller's own _update, letting the seller re-price reserves mid-sell. Fix removes the "
        "mid-transfer pool drain + sync. Reward: PoC exploit oracle must flip PASS->FAIL while "
        "all hidden invariants stay PASS. Verified offline (rpc_replay proxy, 60 slots)."
    ),
)


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "finalize":
        td = Path(sys.argv[2])
        seed = NGP_SEED if td.name == "ngp_2025_09" else json.loads((td / "_seed.json").read_text())
        m = finalize(td, seed)
        print(f"[build_task] finalized {td.name}: split={m.split}, "
              f"{len(m.hash_locks)} harness files hash-locked, "
              f"{len(json.loads((td/'task.json').read_text())['hash_locks'])} locks written")
    else:
        print(__doc__)
