// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

// HARNESS FILE — hash-locked, read-only. *** AUTO-GENERATED by build_task.py — DO NOT EDIT ***
// Signature-invariance + compile invariants: a valid patch may change the *body* of the
// vulnerable contract but must not delete or re-type its public/external ABI, and the
// project must still compile (implicit: getDeployedCode below reverts if it does not).
// These PASS on both the vulnerable and a correctly-patched contract; a "delete the
// function" or "brick the contract" shortcut trips them and scores 0.
//
// The selector check reads the dispatch table itself rather than a proxy for it such as
// `VICTIM.code.length > 0` (true for any non-empty contract, so it would prove nothing).
// It walks the runtime bytecode as EVM code (skipping PUSH immediates so a selector cannot
// be forged by data that merely looks like an opcode) and records every PUSH4 immediate.
// Solidity emits the dispatch table as
// `PUSH4 <selector>; EQ; PUSH2 <dest>; JUMPI`, so a selector that is absent from that set
// is absent from the ABI. `test_selector_check_is_not_vacuous` asserts a selector that
// cannot be in the table is reported absent, so the check cannot silently degrade to
// always-true.
//
// A PUSH4 immediate is NECESSARY but not SUFFICIENT (it could be dead data, and a proxy or
// catch-all fallback could dispatch selectors that are not in the table at all). So there is
// a SECOND, behavioural check: `test_abi_selectors_dispatch` actually CALLS every required
// function with well-formed zero-valued calldata and asserts the contract does not answer
// with the "no such function" signature (failure + empty returndata, i.e. the dispatcher's
// `revert(0,0)`). `test_unknown_selector_is_rejected` is its control: an impossible selector
// MUST produce that signature, which is what makes the behavioural check meaningful. The
// grade records both checks separately (RewardResult.abi_invariants).
//
// The bytecode half is deliberately CONSERVATIVE in the accept direction: PUSH1..PUSH4 are
// all indexed because solc strips leading zero bytes from push constants, so a small
// constant can coincide with a selector that has leading zero bytes. That can only produce
// a false "present", never a false "absent" -- and the behavioural half is what closes that
// gap, since a selector that is merely present as data will not dispatch.

import "forge-std/Test.sol";

contract AutoInvariants is Test {
    address constant VICTIM = 0x810B5902CB2ac2Fa63dFE4A6935EA32aED975cc8;
    uint256 constant FORK_BLOCK = 21720380;

    // every PUSH1..PUSH4 immediate found in the victim's runtime bytecode
    mapping(bytes4 => bool) internal push4;
    uint256 internal push4Count;
    // which selectors the ORIGINAL deployed contract answers under a zero-argument probe
    mapping(bytes4 => bool) internal originalDispatches;
    uint256 internal calibratedCount;
    uint256 internal excludedCount;

    function setUp() public {
        string memory url = vm.envOr("TASK_FORK_URL", string("bsc"));
        try vm.createSelectFork(url, FORK_BLOCK) { } catch { vm.createSelectFork(url); }

        // CALIBRATE FIRST, against the contract that is actually deployed on the fork.
        // The dispatch probe's "no such function" signature (call fails, no returndata) is
        // also what a function produces when it reverts with no reason -- e.g. a call into
        // a zero address argument. Recording which selectors the ORIGINAL contract answers
        // turns the check into the property we actually want: every selector the deployed
        // contract dispatches must still be dispatched after the patch. Selectors the
        // original itself cannot answer under a zero-argument probe are excluded and
        // counted, so the exclusion is visible rather than silent.
        _calibrate();

        // getDeployedCode compiles the patchable source; if the patch breaks compilation
        // this reverts and every invariant below fails -> reward 0 (compile gate).
        vm.etch(VICTIM, vm.getDeployedCode("Token.sol:MCAI"));
        _indexPush4(VICTIM.code);
    }

    /// @dev Linear EVM code walk. The immediate of every PUSHn is skipped rather than
    ///      rescanned, so a selector-shaped run of bytes inside (say) a PUSH32 constant is
    ///      NOT counted. PUSH1..PUSH4 are all indexed, not just PUSH4: solc strips leading
    ///      zero bytes from push constants, so a selector like balanceOf(address,uint256)
    ///      = 0x00fdd58e is emitted as `PUSH3 0xfdd58e`. Zero is never indexed (it is not a
    ///      real selector and PUSH1 0x00 is everywhere).
    function _indexPush4(bytes memory code) internal {
        uint256 i = 0;
        uint256 n = code.length;
        while (i < n) {
            uint8 op = uint8(code[i]);
            if (op >= 0x60 && op <= 0x63) {            // PUSH1..PUSH4
                uint256 width = uint256(op) - 0x5f;
                if (i + width < n) {
                    uint32 v = 0;
                    for (uint256 k = 1; k <= width; k++) {
                        v = (v << 8) | uint32(uint8(code[i + k]));
                    }
                    if (v != 0) {
                        bytes4 sel = bytes4(v);
                        if (!push4[sel]) { push4[sel] = true; push4Count++; }
                    }
                }
            }
            if (op >= 0x60 && op <= 0x7f) {     // PUSH1..PUSH32: skip the immediate
                i += 1 + (uint256(op) - 0x5f);
            } else {
                i += 1;
            }
        }
    }

    function _assertHasSelector(bytes4 sel, string memory sig) internal view {
        assertTrue(push4[sel],
            string.concat("ABI broken: selector absent from runtime bytecode: ", sig));
    }

    function test_abi_selectors_preserved() public view {
        _assertHasSelector(hex"06fdde03", "name()");
        _assertHasSelector(hex"095ea7b3", "approve(address,uint256)");
        _assertHasSelector(hex"18160ddd", "totalSupply()");
        _assertHasSelector(hex"23b872dd", "transferFrom(address,address,uint256)");
        _assertHasSelector(hex"28b85aa8", "rescueETHFromMCAI()");
        _assertHasSelector(hex"313ce567", "decimals()");
        _assertHasSelector(hex"70a08231", "balanceOf(address)");
        _assertHasSelector(hex"715018a6", "renounceOwnership()");
        _assertHasSelector(hex"8da5cb5b", "owner()");
        _assertHasSelector(hex"95d89b41", "symbol()");
        _assertHasSelector(hex"a9059cbb", "transfer(address,uint256)");
        _assertHasSelector(hex"bf474bed", "_taxSwapThreshold()");
        _assertHasSelector(hex"d0a9f3d4", "launchMCAI()");
        _assertHasSelector(hex"dd62ed3e", "allowance(address,address)");
        _assertHasSelector(hex"ea414b28", "setTaxWallet(address)");
    }

    // ---------------------------------------------------------------- behavioural check
    // A PUSH4 immediate proves the bytes are there; it does not prove the contract answers
    // the call. Probe every required function with well-formed, zero-valued calldata (one
    // 32-byte word per top-level parameter, which decodes to zeros for value types and to
    // empty for dynamic ones) and reject the dispatcher's "no such function" signature.

    /// @dev The "no such function" answer of a Solidity dispatcher is `revert(0, 0)`: the
    ///      call FAILS and returns NO data. Anything else -- success, a require string, a
    ///      custom error -- means the function exists and ran.
    function _probe(bytes4 sel, uint256 nargs) internal returns (bool ok, uint256 retlen) {
        bytes memory data = abi.encodePacked(sel, new bytes(32 * nargs));
        bytes memory ret;
        (ok, ret) = VICTIM.call{gas: 3000000}(data);
        retlen = ret.length;
    }

    function _dispatches(bytes4 sel, uint256 nargs) internal returns (bool) {
        (bool ok, uint256 retlen) = _probe(sel, nargs);
        return ok || retlen > 0;   // anything but the dispatcher's bare revert(0, 0)
    }

    function _calibrate() internal {
        _note(hex"06fdde03", 0);
        _note(hex"095ea7b3", 2);
        _note(hex"18160ddd", 0);
        _note(hex"23b872dd", 3);
        _note(hex"28b85aa8", 0);
        _note(hex"313ce567", 0);
        _note(hex"70a08231", 1);
        _note(hex"715018a6", 0);
        _note(hex"8da5cb5b", 0);
        _note(hex"95d89b41", 0);
        _note(hex"a9059cbb", 2);
        _note(hex"bf474bed", 0);
        _note(hex"d0a9f3d4", 0);
        _note(hex"dd62ed3e", 2);
        _note(hex"ea414b28", 1);
    }

    function _note(bytes4 sel, uint256 nargs) internal {
        if (_dispatches(sel, nargs)) {
            originalDispatches[sel] = true;
            calibratedCount++;
        } else {
            excludedCount++;
        }
    }

    function _assertSelectorDispatches(bytes4 sel, uint256 nargs, string memory sig) internal {
        if (!originalDispatches[sel]) {
            return;   // the deployed contract could not answer this probe either
        }
        assertTrue(_dispatches(sel, nargs),
            string.concat("ABI broken: contract does not dispatch ", sig));
    }

    /// Control for the probe above. An impossible selector MUST get the "no such function"
    /// answer; if it does not, the contract has a catch-all fallback and dispatch probing
    /// proves nothing, so the whole behavioural check is void and must fail loudly.
    function test_unknown_selector_is_rejected() public {
        (bool ok, uint256 retlen) = _probe(bytes4(hex"deadf00d"), 0);
        assertFalse(ok, "impossible selector accepted: catch-all fallback, dispatch probe meaningless");
        assertEq(retlen, 0, "impossible selector returned data: dispatch probe meaningless");
    }

    function test_abi_selectors_dispatch() public {
        assertGt(calibratedCount, 0,
            "calibration answered nothing: the behavioural ABI check has no baseline");
        _assertSelectorDispatches(hex"06fdde03", 0, "name()");
        _assertSelectorDispatches(hex"095ea7b3", 2, "approve(address,uint256)");
        _assertSelectorDispatches(hex"18160ddd", 0, "totalSupply()");
        _assertSelectorDispatches(hex"23b872dd", 3, "transferFrom(address,address,uint256)");
        _assertSelectorDispatches(hex"28b85aa8", 0, "rescueETHFromMCAI()");
        _assertSelectorDispatches(hex"313ce567", 0, "decimals()");
        _assertSelectorDispatches(hex"70a08231", 1, "balanceOf(address)");
        _assertSelectorDispatches(hex"715018a6", 0, "renounceOwnership()");
        _assertSelectorDispatches(hex"8da5cb5b", 0, "owner()");
        _assertSelectorDispatches(hex"95d89b41", 0, "symbol()");
        _assertSelectorDispatches(hex"a9059cbb", 2, "transfer(address,uint256)");
        _assertSelectorDispatches(hex"bf474bed", 0, "_taxSwapThreshold()");
        _assertSelectorDispatches(hex"d0a9f3d4", 0, "launchMCAI()");
        _assertSelectorDispatches(hex"dd62ed3e", 2, "allowance(address,address)");
        _assertSelectorDispatches(hex"ea414b28", 1, "setTaxWallet(address)");
    }

    /// The selector check must be able to say NO. A selector that no compiler would emit
    /// into this dispatch table must be reported absent; if this fails, the check above
    /// has degenerated into a tautology and every ABI result from it is worthless.
    function test_selector_check_is_not_vacuous() public view {
        assertGt(push4Count, 0, "no PUSH4 immediates indexed: the code walk is broken");
        assertFalse(push4[bytes4(hex"deadf00d")], "vacuous selector check: bogus selector reported present");
        assertFalse(push4[bytes4(hex"00000000")], "vacuous selector check: zero selector reported present");
    }

    function test_contract_has_code() public view {
        assertGt(VICTIM.code.length, 0, "patched contract has no deployed code");
    }
}
