[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
solc = '0.8.26'
evm_version = 'cancun'
optimizer = false
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
mainnet = "${TASK_RPC_URL}"
