// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

// HARNESS FILE — hash-locked, read-only. *** AUTO-GENERATED by build_task.py — DO NOT EDIT ***
// Signature-invariance + compile invariants: a valid patch may change the *body* of the
// vulnerable contract but must not delete or re-type its public/external ABI, and the
// project must still compile (implicit: getDeployedCode below reverts if it does not).
// These PASS on both the vulnerable and a correctly-patched contract; a "delete the
// function" or "brick the contract" shortcut trips them and scores 0.
//
// The selector check reads the dispatch table itself rather than a proxy for it such as
// `VICTIM.code.length > 0` (true for any non-empty contract, so it would prove nothing).
// It walks the runtime bytecode as EVM code (skipping PUSH immediates so a selector cannot
// be forged by data that merely looks like an opcode) and records every PUSH4 immediate.
// Solidity emits the dispatch table as
// `PUSH4 <selector>; EQ; PUSH2 <dest>; JUMPI`, so a selector that is absent from that set
// is absent from the ABI. `test_selector_check_is_not_vacuous` asserts a selector that
// cannot be in the table is reported absent, so the check cannot silently degrade to
// always-true.
//
// A PUSH4 immediate is NECESSARY but not SUFFICIENT (it could be dead data, and a proxy or
// catch-all fallback could dispatch selectors that are not in the table at all). So there is
// a SECOND, behavioural check: `test_abi_selectors_dispatch` actually CALLS every required
// function with well-formed zero-valued calldata and asserts the contract does not answer
// with the "no such function" signature (failure + empty returndata, i.e. the dispatcher's
// `revert(0,0)`). `test_unknown_selector_is_rejected` is its control: an impossible selector
// MUST produce that signature, which is what makes the behavioural check meaningful. The
// grade records both checks separately (RewardResult.abi_invariants).
//
// The bytecode half is deliberately CONSERVATIVE in the accept direction: PUSH1..PUSH4 are
// all indexed because solc strips leading zero bytes from push constants, so a small
// constant can coincide with a selector that has leading zero bytes. That can only produce
// a false "present", never a false "absent" -- and the behavioural half is what closes that
// gap, since a selector that is merely present as data will not dispatch.

import "forge-std/Test.sol";

contract AutoInvariants is Test {
    address constant VICTIM = 0xd2F26200cD524dB097Cf4ab7cC2E5C38aB6ae5c9;
    uint256 constant FORK_BLOCK = 61515894;

    // every PUSH1..PUSH4 immediate found in the victim's runtime bytecode
    mapping(bytes4 => bool) internal push4;
    uint256 internal push4Count;
    // which selectors the ORIGINAL deployed contract answers under a zero-argument probe
    mapping(bytes4 => bool) internal originalDispatches;
    uint256 internal calibratedCount;
    uint256 internal excludedCount;

    function setUp() public {
        string memory url = vm.envOr("TASK_FORK_URL", string("bsc"));
        try vm.createSelectFork(url, FORK_BLOCK) { } catch { vm.createSelectFork(url); }

        // CALIBRATE FIRST, against the contract that is actually deployed on the fork.
        // The dispatch probe's "no such function" signature (call fails, no returndata) is
        // also what a function produces when it reverts with no reason -- e.g. a call into
        // a zero address argument. Recording which selectors the ORIGINAL contract answers
        // turns the check into the property we actually want: every selector the deployed
        // contract dispatches must still be dispatched after the patch. Selectors the
        // original itself cannot answer under a zero-argument probe are excluded and
        // counted, so the exclusion is visible rather than silent.
        _calibrate();

        // getDeployedCode compiles the patchable source; if the patch breaks compilation
        // this reverts and every invariant below fails -> reward 0 (compile gate).
        vm.etch(VICTIM, vm.getDeployedCode("Token.sol:Token"));
        _indexPush4(VICTIM.code);
    }

    /// @dev Linear EVM code walk. The immediate of every PUSHn is skipped rather than
    ///      rescanned, so a selector-shaped run of bytes inside (say) a PUSH32 constant is
    ///      NOT counted. PUSH1..PUSH4 are all indexed, not just PUSH4: solc strips leading
    ///      zero bytes from push constants, so a selector like balanceOf(address,uint256)
    ///      = 0x00fdd58e is emitted as `PUSH3 0xfdd58e`. Zero is never indexed (it is not a
    ///      real selector and PUSH1 0x00 is everywhere).
    function _indexPush4(bytes memory code) internal {
        uint256 i = 0;
        uint256 n = code.length;
        while (i < n) {
            uint8 op = uint8(code[i]);
            if (op >= 0x60 && op <= 0x63) {            // PUSH1..PUSH4
                uint256 width = uint256(op) - 0x5f;
                if (i + width < n) {
                    uint32 v = 0;
                    for (uint256 k = 1; k <= width; k++) {
                        v = (v << 8) | uint32(uint8(code[i + k]));
                    }
                    if (v != 0) {
                        bytes4 sel = bytes4(v);
                        if (!push4[sel]) { push4[sel] = true; push4Count++; }
                    }
                }
            }
            if (op >= 0x60 && op <= 0x7f) {     // PUSH1..PUSH32: skip the immediate
                i += 1 + (uint256(op) - 0x5f);
            } else {
                i += 1;
            }
        }
    }

    function _assertHasSelector(bytes4 sel, string memory sig) internal view {
        assertTrue(push4[sel],
            string.concat("ABI broken: selector absent from runtime bytecode: ", sig));
    }

    function test_abi_selectors_preserved() public view {
        _assertHasSelector(hex"01ffc9a7", "supportsInterface(bytes4)");
        _assertHasSelector(hex"04ace00e", "setMaxBuyPerDay(uint256)");
        _assertHasSelector(hex"06fdde03", "name()");
        _assertHasSelector(hex"095ea7b3", "approve(address,uint256)");
        _assertHasSelector(hex"0d2d8a31", "lastTransferTime(address)");
        _assertHasSelector(hex"14310f67", "resetBuyRecordBatch(address[])");
        _assertHasSelector(hex"171f56fd", "resetBuyRecord(address)");
        _assertHasSelector(hex"18160ddd", "totalSupply()");
        _assertHasSelector(hex"1acbc2b6", "setMaxBuyAmountInUsdt(uint256)");
        _assertHasSelector(hex"23b872dd", "transferFrom(address,address,uint256)");
        _assertHasSelector(hex"248a9ca3", "getRoleAdmin(bytes32)");
        _assertHasSelector(hex"2e82f1a0", "lpBurnEnabled()");
        _assertHasSelector(hex"2f2ff15d", "grantRole(bytes32,address)");
        _assertHasSelector(hex"30d2361e", "setFeeRates(uint256,uint256,uint256,uint256)");
        _assertHasSelector(hex"313ce567", "decimals()");
        _assertHasSelector(hex"36568abe", "renounceRole(bytes32,address)");
        _assertHasSelector(hex"390adde5", "getBuyInfo(address)");
        _assertHasSelector(hex"3fecc2e2", "lastBuyTime(address)");
        _assertHasSelector(hex"41181c18", "isLpStopBurn()");
        _assertHasSelector(hex"4b94f50e", "getTokenPrice()");
        _assertHasSelector(hex"509bf42a", "burnFeeRate()");
        _assertHasSelector(hex"51613fa3", "sellState()");
        _assertHasSelector(hex"5d2af488", "marketFeeRate()");
        _assertHasSelector(hex"6605bfda", "setTreasuryAddress(address)");
        _assertHasSelector(hex"68f16293", "transferCooldown()");
        _assertHasSelector(hex"70a08231", "balanceOf(address)");
        _assertHasSelector(hex"79341ec2", "setTradeState(bool,bool)");
        _assertHasSelector(hex"7b0a47ee", "rewardRate()");
        _assertHasSelector(hex"7d6a1d4a", "setTransferCooldown(uint256)");
        _assertHasSelector(hex"845a51ec", "rewardPoolAddress()");
        _assertHasSelector(hex"85af30c5", "mainPair()");
        _assertHasSelector(hex"91d14854", "hasRole(bytes32,address)");
        _assertHasSelector(hex"95623641", "marketAddress()");
        _assertHasSelector(hex"95d89b41", "symbol()");
        _assertHasSelector(hex"98d5fdca", "getPrice()");
        _assertHasSelector(hex"9ab4a445", "usdtAddress()");
        _assertHasSelector(hex"9c183f94", "maxBuyAmountInUsdt()");
        _assertHasSelector(hex"9fefe7f4", "buyCount(address)");
        _assertHasSelector(hex"a217fddf", "DEFAULT_ADMIN_ROLE()");
        _assertHasSelector(hex"a58da0be", "setWhitelistBatch(address[],bool)");
        _assertHasSelector(hex"a9059cbb", "transfer(address,uint256)");
        _assertHasSelector(hex"b24cf5d7", "setRewardPoolAddress(address)");
        _assertHasSelector(hex"bcb3eb6f", "buyState()");
        _assertHasSelector(hex"c5f956af", "treasuryAddress()");
        _assertHasSelector(hex"d32867d0", "RATIO_PRECISION()");
        _assertHasSelector(hex"d5391393", "MINTER_ROLE()");
        _assertHasSelector(hex"d547741f", "revokeRole(bytes32,address)");
        _assertHasSelector(hex"d936547e", "whitelisted(address)");
        _assertHasSelector(hex"dd62ed3e", "allowance(address,address)");
        _assertHasSelector(hex"e10fbc08", "maxBuyPerDay()");
        _assertHasSelector(hex"e146a7fe", "setLpBurnEnabled(bool)");
        _assertHasSelector(hex"e4b72516", "treasuryRate()");
        _assertHasSelector(hex"fae92612", "setMarketAddress(address)");
    }

    // ---------------------------------------------------------------- behavioural check
    // A PUSH4 immediate proves the bytes are there; it does not prove the contract answers
    // the call. Probe every required function with well-formed, zero-valued calldata (one
    // 32-byte word per top-level parameter, which decodes to zeros for value types and to
    // empty for dynamic ones) and reject the dispatcher's "no such function" signature.

    /// @dev The "no such function" answer of a Solidity dispatcher is `revert(0, 0)`: the
    ///      call FAILS and returns NO data. Anything else -- success, a require string, a
    ///      custom error -- means the function exists and ran.
    function _probe(bytes4 sel, uint256 nargs) internal returns (bool ok, uint256 retlen) {
        bytes memory data = abi.encodePacked(sel, new bytes(32 * nargs));
        bytes memory ret;
        (ok, ret) = VICTIM.call{gas: 3000000}(data);
        retlen = ret.length;
    }

    function _dispatches(bytes4 sel, uint256 nargs) internal returns (bool) {
        (bool ok, uint256 retlen) = _probe(sel, nargs);
        return ok || retlen > 0;   // anything but the dispatcher's bare revert(0, 0)
    }

    function _calibrate() internal {
        _note(hex"01ffc9a7", 1);
        _note(hex"04ace00e", 1);
        _note(hex"06fdde03", 0);
        _note(hex"095ea7b3", 2);
        _note(hex"0d2d8a31", 1);
        _note(hex"14310f67", 1);
        _note(hex"171f56fd", 1);
        _note(hex"18160ddd", 0);
        _note(hex"1acbc2b6", 1);
        _note(hex"23b872dd", 3);
        _note(hex"248a9ca3", 1);
        _note(hex"2e82f1a0", 0);
        _note(hex"2f2ff15d", 2);
        _note(hex"30d2361e", 4);
        _note(hex"313ce567", 0);
        _note(hex"36568abe", 2);
        _note(hex"390adde5", 1);
        _note(hex"3fecc2e2", 1);
        _note(hex"41181c18", 0);
        _note(hex"4b94f50e", 0);
        _note(hex"509bf42a", 0);
        _note(hex"51613fa3", 0);
        _note(hex"5d2af488", 0);
        _note(hex"6605bfda", 1);
        _note(hex"68f16293", 0);
        _note(hex"70a08231", 1);
        _note(hex"79341ec2", 2);
        _note(hex"7b0a47ee", 0);
        _note(hex"7d6a1d4a", 1);
        _note(hex"845a51ec", 0);
        _note(hex"85af30c5", 0);
        _note(hex"91d14854", 2);
        _note(hex"95623641", 0);
        _note(hex"95d89b41", 0);
        _note(hex"98d5fdca", 0);
        _note(hex"9ab4a445", 0);
        _note(hex"9c183f94", 0);
        _note(hex"9fefe7f4", 1);
        _note(hex"a217fddf", 0);
        _note(hex"a58da0be", 2);
        _note(hex"a9059cbb", 2);
        _note(hex"b24cf5d7", 1);
        _note(hex"bcb3eb6f", 0);
        _note(hex"c5f956af", 0);
        _note(hex"d32867d0", 0);
        _note(hex"d5391393", 0);
        _note(hex"d547741f", 2);
        _note(hex"d936547e", 1);
        _note(hex"dd62ed3e", 2);
        _note(hex"e10fbc08", 0);
        _note(hex"e146a7fe", 1);
        _note(hex"e4b72516", 0);
        _note(hex"fae92612", 1);
    }

    function _note(bytes4 sel, uint256 nargs) internal {
        if (_dispatches(sel, nargs)) {
            originalDispatches[sel] = true;
            calibratedCount++;
        } else {
            excludedCount++;
        }
    }

    function _assertSelectorDispatches(bytes4 sel, uint256 nargs, string memory sig) internal {
        if (!originalDispatches[sel]) {
            return;   // the deployed contract could not answer this probe either
        }
        assertTrue(_dispatches(sel, nargs),
            string.concat("ABI broken: contract does not dispatch ", sig));
    }

    /// Control for the probe above. An impossible selector MUST get the "no such function"
    /// answer; if it does not, the contract has a catch-all fallback and dispatch probing
    /// proves nothing, so the whole behavioural check is void and must fail loudly.
    function test_unknown_selector_is_rejected() public {
        (bool ok, uint256 retlen) = _probe(bytes4(hex"deadf00d"), 0);
        assertFalse(ok, "impossible selector accepted: catch-all fallback, dispatch probe meaningless");
        assertEq(retlen, 0, "impossible selector returned data: dispatch probe meaningless");
    }

    function test_abi_selectors_dispatch() public {
        assertGt(calibratedCount, 0,
            "calibration answered nothing: the behavioural ABI check has no baseline");
        _assertSelectorDispatches(hex"01ffc9a7", 1, "supportsInterface(bytes4)");
        _assertSelectorDispatches(hex"04ace00e", 1, "setMaxBuyPerDay(uint256)");
        _assertSelectorDispatches(hex"06fdde03", 0, "name()");
        _assertSelectorDispatches(hex"095ea7b3", 2, "approve(address,uint256)");
        _assertSelectorDispatches(hex"0d2d8a31", 1, "lastTransferTime(address)");
        _assertSelectorDispatches(hex"14310f67", 1, "resetBuyRecordBatch(address[])");
        _assertSelectorDispatches(hex"171f56fd", 1, "resetBuyRecord(address)");
        _assertSelectorDispatches(hex"18160ddd", 0, "totalSupply()");
        _assertSelectorDispatches(hex"1acbc2b6", 1, "setMaxBuyAmountInUsdt(uint256)");
        _assertSelectorDispatches(hex"23b872dd", 3, "transferFrom(address,address,uint256)");
        _assertSelectorDispatches(hex"248a9ca3", 1, "getRoleAdmin(bytes32)");
        _assertSelectorDispatches(hex"2e82f1a0", 0, "lpBurnEnabled()");
        _assertSelectorDispatches(hex"2f2ff15d", 2, "grantRole(bytes32,address)");
        _assertSelectorDispatches(hex"30d2361e", 4, "setFeeRates(uint256,uint256,uint256,uint256)");
        _assertSelectorDispatches(hex"313ce567", 0, "decimals()");
        _assertSelectorDispatches(hex"36568abe", 2, "renounceRole(bytes32,address)");
        _assertSelectorDispatches(hex"390adde5", 1, "getBuyInfo(address)");
        _assertSelectorDispatches(hex"3fecc2e2", 1, "lastBuyTime(address)");
        _assertSelectorDispatches(hex"41181c18", 0, "isLpStopBurn()");
        _assertSelectorDispatches(hex"4b94f50e", 0, "getTokenPrice()");
        _assertSelectorDispatches(hex"509bf42a", 0, "burnFeeRate()");
        _assertSelectorDispatches(hex"51613fa3", 0, "sellState()");
        _assertSelectorDispatches(hex"5d2af488", 0, "marketFeeRate()");
        _assertSelectorDispatches(hex"6605bfda", 1, "setTreasuryAddress(address)");
        _assertSelectorDispatches(hex"68f16293", 0, "transferCooldown()");
        _assertSelectorDispatches(hex"70a08231", 1, "balanceOf(address)");
        _assertSelectorDispatches(hex"79341ec2", 2, "setTradeState(bool,bool)");
        _assertSelectorDispatches(hex"7b0a47ee", 0, "rewardRate()");
        _assertSelectorDispatches(hex"7d6a1d4a", 1, "setTransferCooldown(uint256)");
        _assertSelectorDispatches(hex"845a51ec", 0, "rewardPoolAddress()");
        _assertSelectorDispatches(hex"85af30c5", 0, "mainPair()");
        _assertSelectorDispatches(hex"91d14854", 2, "hasRole(bytes32,address)");
        _assertSelectorDispatches(hex"95623641", 0, "marketAddress()");
        _assertSelectorDispatches(hex"95d89b41", 0, "symbol()");
        _assertSelectorDispatches(hex"98d5fdca", 0, "getPrice()");
        _assertSelectorDispatches(hex"9ab4a445", 0, "usdtAddress()");
        _assertSelectorDispatches(hex"9c183f94", 0, "maxBuyAmountInUsdt()");
        _assertSelectorDispatches(hex"9fefe7f4", 1, "buyCount(address)");
        _assertSelectorDispatches(hex"a217fddf", 0, "DEFAULT_ADMIN_ROLE()");
        _assertSelectorDispatches(hex"a58da0be", 2, "setWhitelistBatch(address[],bool)");
        _assertSelectorDispatches(hex"a9059cbb", 2, "transfer(address,uint256)");
        _assertSelectorDispatches(hex"b24cf5d7", 1, "setRewardPoolAddress(address)");
        _assertSelectorDispatches(hex"bcb3eb6f", 0, "buyState()");
        _assertSelectorDispatches(hex"c5f956af", 0, "treasuryAddress()");
        _assertSelectorDispatches(hex"d32867d0", 0, "RATIO_PRECISION()");
        _assertSelectorDispatches(hex"d5391393", 0, "MINTER_ROLE()");
        _assertSelectorDispatches(hex"d547741f", 2, "revokeRole(bytes32,address)");
        _assertSelectorDispatches(hex"d936547e", 1, "whitelisted(address)");
        _assertSelectorDispatches(hex"dd62ed3e", 2, "allowance(address,address)");
        _assertSelectorDispatches(hex"e10fbc08", 0, "maxBuyPerDay()");
        _assertSelectorDispatches(hex"e146a7fe", 1, "setLpBurnEnabled(bool)");
        _assertSelectorDispatches(hex"e4b72516", 0, "treasuryRate()");
        _assertSelectorDispatches(hex"fae92612", 1, "setMarketAddress(address)");
    }

    /// The selector check must be able to say NO. A selector that no compiler would emit
    /// into this dispatch table must be reported absent; if this fails, the check above
    /// has degenerated into a tautology and every ABI result from it is worthless.
    function test_selector_check_is_not_vacuous() public view {
        assertGt(push4Count, 0, "no PUSH4 immediates indexed: the code walk is broken");
        assertFalse(push4[bytes4(hex"deadf00d")], "vacuous selector check: bogus selector reported present");
        assertFalse(push4[bytes4(hex"00000000")], "vacuous selector check: zero selector reported present");
    }

    function test_contract_has_code() public view {
        assertGt(VICTIM.code.length, 0, "patched contract has no deployed code");
    }
}
